### ISSUE TITLE
Ability To Star Favorite Courses 

### ISSUE THREAD

**Issue by ZamZao** [zero-to-mastery/zero-to-mastery#12]
Hey ZTM team, 

For our greater pleasure, there is a lot of courses to choose from and I can see myself taking all of them sooner or later, 

However, navigation has become a little bit more painful. 

I think it is time to add the possibility to put courses in a favourite list, like starring them.

I was wondering if anyone is working on the feature above? as part of my training, I am willing to work on it if you guys allow me

**Comment by MattCSmith** [comment]
Thanks for the suggestion @ZamZao, I have passed this suggestion onto the Academy team. 
For reference the best place for suggestions would be in the community Discord.
Thanks again
